[package]
name = "certigrad"
version = "0.1"
path = "src"

[dependencies]
library_dev_extras = {git = "https://github.com/dselsam/library_dev_extras.git", rev = "302d631dfc40c6d69f921fd7bacf017e11e6e56c"}
